run:
  timeout: 30m

output:
  format: line-number

linters-settings:
  revive:
    rules:
    - name: dot-imports
      exclude: ["**/*_test.go"]

linters:
  disable-all: false
  enable:
  - bodyclose
  - dogsled
  - errcheck
  - exportloopref
  - gocognit
  - goconst
  - gocritic
  - godox
  - gofmt
  - goimports
  - gosec
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nakedret
  - revive
  - staticcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - whitespace
  - reassign
