project_name: firehose_exporter

builds:
  - id: binary
    dir: .
    main: ./firehose_exporter.go
    binary: firehose_exporter
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.Revision={{.FullCommit}}
      - -X github.com/prometheus/common/version.Branch={{.Branch}}
      - -X github.com/prometheus/common/version.BuildUser={{.Env.USER}}
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
      - -X code.cloudfoundry.org/cli/version/binaryVersion={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
      - ppc64
      - ppc64le
    goarm: [5,6,7]
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: ppc64
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: ppc64
      - goos: windows
        goarch: ppc64le

archives:
  - id: archives
    builds: [binary]
    format: "tar.gz"
    name_template: '{{ .ProjectName }}_{{ .Version }}.{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}'
    wrap_in_directory: true
    files:
      - LICENSE
      - NOTICE
      - README*
      - CHANGELOG*
      - docs/*
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - 'docs'
    - '\.md'

checksum:
  name_template: checksums.txt
  algorithm: sha256

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: ./Dockerfile
    image_templates:
      - "boshprometheus/firehose-exporter:latest"
      - "boshprometheus/firehose-exporter:{{ .Tag }}"
      - "boshprometheus/firehose-exporter:v{{ .Major }}"
      - "boshprometheus/firehose-exporter:v{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

release:
  prerelease: auto
  name_template: '{{.Tag}}'
